### PR TITLE
cloning cabinets

### PR DESCRIPTION
**Pull request by KaeLhun**
my first amateur modification and my first attempt to publish something on GitHub. 
You can see a realtime demonstration here: http://www.youtube.com/watch?v=BFHQWQHsKhI
Maybe not too elegant but works. I'm not professional developer I just able to customize others sources for my needs.

### CODE REVIEW

**Comment by wilpig** [comment]
I'll look this over tonight. I see it's using the mysql connect method instead of the pdo connection and that will have to be altered and see if the sql can be moved into the class as a method.

**Comment by KaeLhun** [comment]
Thanks for the comment. I've copied from an other source (I couldn't write like this from myself) and somehow only worked this mysql connect addition. I know it shouldn't be...

**Comment by KaeLhun** [comment]
I've returned to this project, in hope that somebody fixed the mysql connect method and fully implemented this function to openDCIM. 
Unfortunately I still don't have that knowledge so please who has, solve this problem for the community. It is a great feature and almost ready to use. 
Thank you.

**Comment by samilliken** [comment]
I will likely implement this (or something very similar) in 4.5.

**Comment by samilliken** [comment]
Stale PR that can't be resolved.

**Pull request closed without merging**
