### PR TITLE
gauge.draw: check for locale-related bug

### PR DESCRIPTION
**Pull request by spezialist1**
One more decision for elimination of a problem with a locale: if the locale is other than en_US, gauge incorrectly displays power consumption.

Very thanks for the support.

### CODE REVIEW

**Comment by wilpig** [comment]
The current version is using %d which returns an int and not a decimal number so you're converting them to floats instead but if you wanted to use a float for the decimal precision why not just use F 
``` F - the argument is treated as a float, and presented as a floating-point number (non-locale aware). Available since PHP 4.3.10 and PHP 5.0.3. ```

**Comment by spezialist1** [comment]
Wilbur, I not for nothing used float numbers with localization. If to use int numbers as you made it, such bug turns out here:
gauge_en_err

I think it is necessary to explain more than nothing, gauge need to be corrected. Any ideas?

Very thanks for the support.

**Comment by spezialist1** [comment]
Wilbur, Panel Voltage in Configuration and Power Panel pages, is phase to neutral voltage or phase to phase voltage?

If Panel Voltage is phase to phase voltage, then gauge need to be corrected as there it is supposed, Panel Voltage is phase to neutral voltage.

Very thanks for the support.

**Comment by samilliken** [comment]
It should be your supply voltage, that way the math works out correctly -
if you have a 2 or 3  pole breaker, it calculates as phase to phase; while
if you have a single pole breaker, it will calculate as phase to neutral.

Scott

**Comment by spezialist1** [comment]
Well, I have single pole breaker therefore, following your Scott logic, I specify phase to neutral voltage in Configuration page. Correctly?
Then tell and comment, please, the next lines from these scripts:

-- cabnavigator.php (lines 478-484);
-- infrastructure.inc.php (lines 514-520);
-- ajax_tooltip.php (lines 159-165);
-- power_panel.php(line 57).

How you think Scott, where the power of single pole breaker will be correctly calculated? In my opinion _anywhere_.

Very thanks for the support.

**Comment by samilliken** [comment]
No, and maybe I need to be educated about power systems in your country -
which I readily admit to knowing little about.

I have a 208VAC supply to my panel.  That is what I would get in a
phase-to-phase configuration.  Phase to neutral would be 208 / sqrt(3) =
120VAC.  The only place where we perform power calculations is in a single
pole (phase to neutral) configuration for voltage, or in three-phase for
load (average of Amperes * voltage / sqrt(3) = load).

Scott

**Comment by spezialist1** [comment]
Scott, you understand that your answer is very confused :-).

Let's say in DC all breakers only of one size are used (only single pole or only three pole). Then still it is possible to define experimentally what voltage needs to be specified for the Panel Voltage on Configuration page. And everything will be Ok.

But so not often happens. After all almost in any DC in cabinets rPDU are used single pole breakers, and in the UPS input/output and modular PDU are used three pole breakers. You understand? What then voltage to specify on Configuration page? Anyway, for breakers of one type max power will be calculated correctly, and for others type of breakers it is wrong. Do you agree?

Very thanks for the support.

**Comment by spezialist1** [comment]
Wilbur, see my pool request #665.

Very thanks for the support.

**Pull request closed without merging**
