### PR TITLE
Pue and DCEM

### PR DESCRIPTION
**Pull request by MorinPierre**

### CODE REVIEW

**Comment by spezialist1** [comment]
Pierre,

explain, please, for what the third table fac_ElectricalMeasurePoint in addition to two other tables fac_SNMPElectricalMeasurePoint and fac_ModbusElectricalMeasurePoint was added?

And why for Cooling MP and Air MP it is used only on two tables in that case (for SNMP and Modbus)?

Very thanks for the support.

**Comment by MorinPierre** [comment]
I split measure points representation in three layers. In the first one you have the MeasurePoint class which contains general informations. In the second one I specify what the MeasurePoint will measure (electricity, cooling or air). There is a class for each type of measure (ElectricalMeasurePoint, CoolingMeasurePoint and AirMeasurePoint) that you can find in measure.inc.php. The tables fac_CoolingMeasurePoint and fac_AirMeasurePoint are absent from the database because for now there are not any attribute for them. The reasons you can find those two classes in measure.inc.php are to keep a symetric class organisation and simplify evolutions.
Then on the third layer there are communication classes (SNMP and Modbus) which contains informations to poll equipments.
This organisation has the advantage to simplify the creation of classes for new type of measures or new type of communication.
If I'm not clear, tell me. I'll try to explain another way. :)

**Comment by spezialist1** [comment]
Thanks for a good explanation :-).

Thus, if it is necessary to use multipliers for Air MP and Cooling MP now, there will be a need for creation of the additional tables: fac_AirMeasurePoint and fac_CoolingMeasurePoint. I correctly understood you?

Very thanks for the support.

**Comment by MorinPierre** [comment]
Yes, that's right.

**Pull request merged**
