### PR TITLE
Add Patch panels Ports Usage to ToolTips...

### PR DESCRIPTION
**Pull request by spezialist1**
cabnavigator
Add Patch panels Ports Usage to ToolTips...

### CODE REVIEW

**Comment by spezialist1** [comment]
tooltip

**Comment by samilliken** [comment]
This is too specialized to go in as a default function within the application.  Why would you implement a count of patch panel ports and not switch ports?  Would you look at only ethernet switches or also SAN switches?  There are way too many variables to make this a *Cabinet Metric*.

**Comment by spezialist1** [comment]
Good question... Half a year ago I already wrote here about need to add one more metrics: usage of ports in the patch panels of cabinet. I was answered that it will be realized in future openDCIM versions through the user or custom settings (the user will be able to adjust itself a look in cabnavigator). But time passed, and and changed nothing.

Now why patch panels, but not switch and other? I simply rely on the experience in DCs: also I can tell that in 95% of cases the greatest interest for the service personnel causes usage of ports of the patch panels in cabinets. And for this reason, for example, in APC Data Center Operation made display of usage of ports patch panels, but not something another...

Of course, the idea to calculate usage of ports of switch and the other equipment came to my mind. It is good idea and I am ready to realize it. But, need for it still small, and here usage of ports patch panels in cabinets is that that is necessary already __now__, but not in the future...

**Comment by spezialist1** [comment]
I about it initiated vote on openDCIM Mailing Lists. It is interesting to learn opinion of users of the project...

**Pull request closed without merging**
