### PR TITLE
Display date in ISO format

### PR DESCRIPTION
**Pull request by WoMec**
I changed the display format to ISO standart. Every thing works fine, but I'm not able to find, where change setting of datepicker (js calendar popup) to parse date in ISO format and return picked dated in same format. Maybe someone with more skills with JS can help. 

Thank you.

### CODE REVIEW

**Comment by wilpig** [comment]
http://api.jqueryui.com/datepicker/#option-dateFormat

**Comment by wilpig** [comment]
Also this links back to an old issue, tagging it here for the record #83

**Comment by WoMec** [comment]
devices.php - **updated** 

**to be done ...** 

report_surplus.php
report_audit_frequency.php
report_audit.php
project_mgr.php
cabinets.php 
rackrequest.php

**Comment by wilpig** [comment]
Thanks that looks awesome so far.

**Comment by WoMec** [comment]
All files using datepicker shoud be updated...

devices.php
report_surplus.php
report_audit_frequency.php
report_audit.php
project_mgr.php
cabinets.php
rackrequest.php

**Comment by mik0s** [comment]
Hello. I upgrade from 4.3.1 to last release from git and have error on datepicker :(
opendcim-datepicker-error
Why?

PS: Apache restarted.

**Comment by wilpig** [comment]
Because I hate you and your browser cache hates you more than me.  Please use the discussion list for questions and only pull the latest bleeding edge code from github if you are trying to do devlopment or have been requested to pull it specifically for beta testing.

**Pull request merged**
