### PR TITLE
Some bug fix in FPDF-reports and other...

### PR DESCRIPTION
**Pull request by spezialist1**
Hi all!

I made some bug fix in FPDF-reports, added Ukrainian translation, added cyrillic fonts for reports and so on. Comments are welcomed :-).

### CODE REVIEW

**Comment by samilliken** [comment]
We are no longer using fPDF because the project is no longer maintained.  If you want to make enhancements, it should be using the mPDF library, which is already merged into the source.

**Comment by wilpig** [comment]
I'll look at this more when I get home.  It doesn't really look like enhancements with the exception of the font loading.

**Comment by samilliken** [comment]
Now that I've looked closer, I agree.

**Comment by spezialist1** [comment]
Hi all!

I know that FPDF Library more isn't supported any more. But until current reports of openDCIM are converted to mPDF will pass some time... For now I found time and led them to a normal view with use of the locale other than en_US, for examle uk_UA or ru_RU and other.

Anyway, thanks for that was included my corrections of a program code in openDCIM project. Besides, I confirm that from this point I also will be engaged further in the translation of openDCIM into Ukrainian :-).

Now I am worked in practical implementation of openDCIM in one of banks of Ukraine for two DC's. In DC's almost all power equipment of production APC, and IT equipment of production IBM. And I have a lot of useful information for further development and upgrade of our project.

For example, in openDCIM possibility of obtaining information on the virtual machines VMware ESX is already realized. Similarly, it would be very cool if we still realized possibility of obtaining information on the virtual machines on the IBM servers under control of AIX OS, i.e. about LPAR's. LPAR on IBM AIX is too most that the virtual machine on the VMware ESX server...

**Comment by samilliken** [comment]
Spezialist1,
        If you know the 'how' of getting the virtual machine/LPAR
information out of AIX then we could make that happen.  The problem is that
we don't have an AIX system to test against.  If you do (and it sounds like
you do) then if you can write the script to gather than information (would
need to be able to run from the openDCIM web server - not on the AIX box
itself) we can integrate it.  As for the mPDF/fPDF - yes, once I realized
that it was minor, we merged the request in, and were VERY thankful for the
Ukrainian translation and the fact that you added the translation functions
into the report.

Scott

**Comment by spezialist1** [comment]
Hi Scott.

Unfortunately, I don't know yet as to read information about of AIX LPAR's. So far I know that it won't be possible to use the SNMP protocol :-(. As option, I want to address to the lpar2rrd project, perhaps it will push me on the solution of the task... At least, it is very interesting to me.

Besides, it is the truth, I have an access to AIX systems to test openDCIM together with the various IBM equipment: already there are some practices on templates of the equipment of this vendor. As soon as I prepare all necessary information on templates (IBM and APC), I will surely upload on GitHub.

**Pull request merged**
