### PR TITLE
API: cabinet post route fix

### PR DESCRIPTION
**Pull request by jaroslawp**
This PR makes put/post API routes for cabinet functionning same way as other routes.

### CODE REVIEW

**Comment by wilpig** [comment]
This doesn't fix the routes.  The put should be a create cabinet operation in which case you wouldnt' supply an ID the ID would be created with the new records.

The post operation should be an update operation and this only has the get code for getting the record.  Adding the ID is correct here but the rest of the function to update the cabinet is missing.

**Comment by jaroslawp** [comment]
Ah indeed, one patch too many (removed unwanted id in PUT route).
For the POST operation, I'm not sure I understand ? - the rest seems to be already defined in 
alreaady existing code ? (there is a call to `$cab->UpdateCabinet` in `postRoutes.php` and `UpdateCabinet` is defined in `Cabinet.class.php` ? )

**Comment by wilpig** [comment]
The tree didn't load far enough on my phone. That's my mistake for not clicking again.

**Comment by jaroslawp** [comment]
OK, that should be fixed now.

**Pull request merged**
