### PR TITLE
Display MeasurePoints in their linked equipments + multipliers for Air and Cooling MeasurePoints attributes

### PR DESCRIPTION
**Pull request by MorinPierre**

### CODE REVIEW

**Comment by spezialist1** [comment]
Good work, especially concerning multipliers for AirMP and CoolingMP!

However, there is one bug: for example, there are two ElectricalMP, and on one of them zero readings of power and energy, and on another not zero readings. If in Graph Generator to select both of these ElectricalMP, the graph window doesn't appear at all. If deselect ElectricalMP with zero readings, the graph is normally drawn.

Any idea?..
Very thanks for the support.

**Comment by MorinPierre** [comment]
There is probably a javascript error. If it's not javascript then it's the ajax query that fails (in scripts/ajax_graphs.php).

I opened the issue tab in my page of the project. I think it could be more simple to discuss.

Thank you for being my beta tester

**Comment by MorinPierre** [comment]
I fixed it by not displaying empty measure points in the list.

**Comment by spezialist1** [comment]
Always please :-), especially with my real application in DCs.

And above the specified fixed is already executed?

Strange, but on the https://github.com/MorinPierre/openDCIM/issues page I don't see any issue...

Very thanks for the support.

**Comment by MorinPierre** [comment]
I didn't commit the fix yet. I'll do it soon.

I meant that i activated the issue page as it isn't enabled by default.

**Comment by spezialist1** [comment]
Besides, after this pull request, in Graph Generator zero value of energy is displayed. I checked: value of energy is normally reading each hour and write in a database. In what there can be a problem?

Very thanks for the support.

**Pull request merged**
