### PR TITLE
Update devices.php

### PR DESCRIPTION
**Pull request by WoMec**
fix of right to delete devices.

### CODE REVIEW

**Comment by samilliken** [comment]
Thanks for catching that!

**Comment by wilpig** [comment]
That was supposed to be an or.  Because the delete right is global like read. So you could have someone that has gonna read and delete, but if someone didn't have delete they could at least remove their own shit

**Comment by samilliken** [comment]
I was pretty sure that we were keeping delete abilities separate from
simply modifying even your own devices.

Scott

**Comment by wilpig** [comment]
Then you better go change the API to match because it clearly uses the behavior I described

https://github.com/samilliken/openDCIM/blob/master/api/v1/deleteRoutes.php#L128

**Pull request merged**
