### PR TITLE
Dockerize, Full compatiblity with nginx

### PR DESCRIPTION
**Pull request by pouyanh**
- Dockerize it on an alpine image (php-fpm + nginx)
- Full compatibility with nginx
- Gitlab CI Build and Release Tasks
- API:
  - Accept apikey to authenticate user and authorize access
  - /container route
- Compatibility with php gettext, intl

### CODE REVIEW

**Comment by wilpig** [comment]
We're not converting this all over to docker.

**Comment by pouyanh** [comment]
It's an option beside nginx compatibility and other features that I've mentioned

**Comment by wilpig** [comment]
It's not an option when you start changing the defaults.

https://github.com/samilliken/openDCIM/pull/967/files#diff-74412f34fe15a0da8fdc8d67873794d6R38

You also didn't update the preflight to support nginx/docker you just changed it.

No.

**Comment by pouyanh** [comment]
By adding nginx compatibility I meant:
  - Defining the **apache_request_headers** method which is not present when you run it on nginx: https://github.com/samilliken/openDCIM/pull/967/files#diff-4cd9fb4096d52791a665561dab49815dR36
  - Defining the practical **nginx/site.conf**: https://github.com/samilliken/openDCIM/pull/967/files#diff-3ea2de86a0dbd979d8115af2bfaeaa54
  - Providing a sample *fastcgi_params*: https://github.com/samilliken/openDCIM/pull/967/files#diff-0430bf89de252fe2530caf47b71e6883
  - This was just fixing a typo in preflight: https://github.com/samilliken/openDCIM/pull/967/files#diff-81500676f0e203b6ff19f10e5103be0cR239
  - And reading auth headers which are set by fastcgi: https://github.com/samilliken/openDCIM/pull/967/files#diff-338f728bfb61a67a300a30c4f31f50dfR845

At last it's up to you to learn how enterprise softwares needs to be developed or developing a software which won't run correctly on any environment except your own laptop

**Pull request closed without merging**
