### PR TITLE
De-rate all breakers to Power Critical % (from configuration page) su…

### PR DESCRIPTION
**Pull request by spezialist1**
…stained load

Improvement: de-rate all breakers to Power Critical % (from configuration page) sustained load, instead of hardcoded of 80%...

### CODE REVIEW

**Comment by wilpig** [comment]
I'm pretty sure the de-rating has nothing to do with the critical value.  I'll defer this to scott.

**Comment by samilliken** [comment]
Standard ratings for breakers are such that you can only sustain 80% load,
and anything over that 80% has a time based curve before it will eventually
trigger the breaker mechanism.  This is why we hard coded the 80% - not
enough people realize that a 30A 3-phase breaker can only hold a sustained
load of 8.6 kW, and anything over that amount would essentially start a
clock until the breaker gets hot enough to trigger.  For this reason we've
never exposed that derating as a configuration item.

**Comment by spezialist1** [comment]
Scott, I well thought and I can tell that I agree with the given arguments and explanations: I didn't consider well change....

Therefore I cancel this pull request as wrong.

P.S.: Scott, and as relatively add pull request #601 and an updated Ukrainian translation from getlocalization to openDCIM-master?

Very thanks for the support.

**Comment by wilpig** [comment]
I just pushed up the latest translations.

**Comment by spezialist1** [comment]
Wilbur I successfully translated five new strings into Ukrainian.

**Pull request closed without merging**
