### PR TITLE
Cdu snmp names status

### PR DESCRIPTION
**Pull request by timlegge**

### CODE REVIEW

**Comment by timlegge** [comment]
I have cleaned up the devices.php and attempted to make the refreshswitch to be more generic to work for both the switch and CDU and renamed it refreshdevice.  If you have concerns or a preferred method let me know.  There was a lot of code duplication sever commits earlier and this is smaller but possibly worse.

Please give it a look.  I have tested the snmp against a simulated APC CDU and against a real cisco switch.

Tim

**Comment by timlegge** [comment]
@samilliken @wilpig This Pull request has a number of commits which might make it a pain to review.  If you like I can squash some or all of the commits.  Essentially it could be one commit to add support for getting the CDU portnames, user description and status of ports where it is supported.

**Comment by wilpig** [comment]
We don't generally look at the specific commits but review by the changes view.

On Sep 2, 2019 5:16 PM, Timothy Legge <notifications@github.com> wrote:

@samilliken<https://github.com/samilliken> @wilpig<https://github.com/wilpig> This Pull request has a number of commits which might make it a pain to review. If you like I can squash some or all of the commits. Essentially it could be one commit to add support for getting the CDU portnames, user description and status of ports where it is supported.

**Comment by timlegge** [comment]
@wilpig thanks for the reply.  I know you guys are busy but do you have a feel for whether this (or some variation) would be accepted?  I am getting ready to use it in my production version and would like to avoid having to continuously merge my changes on top of future versions.  

I suspect my changes to devices.php would be the most concerning.  If I thought I needed to maintain it separately I would likely go back to more duplicate code to make maintaining it separately easier.

regards

Tim

**Comment by wilpig** [comment]
Scott and I are both busy so we'll get to it eventually. Sorry I don't have a better timeline. As long as it doesn't break current processes as doesn't create a ton of support requests it'll likely get merged.

On Sep 4, 2019 11:18 AM, Timothy Legge <notifications@github.com> wrote:

@wilpig<https://github.com/wilpig> thanks for the reply. I know you guys are busy but do you have a feel for whether this (or some variation) would be accepted? I am getting ready to use it in my production version and would like to avoid having to continuously merge my changes on top of future versions.

I suspect my changes to devices.php would be the most concerning. If I thought I needed to maintain it separately I would likely go back to more duplicate code to make maintaining it separately easier.

regards

Tim

**Comment by timlegge** [comment]
I will take that as quite likely!  I tied it as close to existing code as I could I think it will be okay.  I tend to drop in an out of projects as I have an itch to scratch but I will keep an eye out for issues for things I have added.  Thanks.

Tim

**Comment by timlegge** [comment]
the last three commits resolve known issues after I applied the changes to my environment

**Pull request merged**
