### PR TITLE
Add start any number on first unit

### PR DESCRIPTION
**Pull request by dc-admin**
This patch add numbering cabs on any unit number (required for hanging cabinets with numbering from the floor).

### CODE REVIEW

**Comment by wilpig** [comment]
Please submit a screenshot and description as to why this is needed and should be merged.  As it stands I see no valid use case for added complication.

**Comment by samilliken** [comment]
Not only that you can't go changing the db update file for an already released version.

**Comment by dc-admin** [comment]
scr1
scr2
scr3
scr4

**Comment by wilpig** [comment]
- I'm still waiting for the use case of why.  I know you said for hanging cabinets on a wall.  Generally those cabinets come numbered starting at 1, so you've renumbered them and want to document it?  
- Does this patch handle the reverse numbered cabinets as well?   
- Honestly i'm shocked that the devices inserted into the cabinet correctly, I didn't think I made that code that robust to handle such craziness
- obviously the tipping point calculations for this type of setup are completely useless and should probably be hidden, but that is making an assumption that this is truly mounted to a wall and not just stacked on top of another cabinet.
- stacked cabinets would be an obvious use case for this **HOWEVER** I point back to they are generally numbered starting with 1

**Comment by samilliken** [comment]
I'm leaning towards saying that this shouldn't be a patch into the main
distributed code of openDCIM.  It will create more questions than answers.

Scott

**Comment by dc-admin** [comment]
Ok, if I create a new patch, taking into account all of your comments, it has a chance to get into the upstream?

**Comment by wilpig** [comment]
I don't have a major issue with it, but these are several issues we've had with this particular section of the code already.  These are also some of the same questions we'll have to answer about it later.

**Comment by wilpig** [comment]
S.U.T.  What happens when a user sets that first U value to 0 or god a negative number?   **They really do this kinda nonsense**

**Comment by dc-admin** [comment]
CabinetsCabinets are stacked in two rows, the top row is bolted to the beams, the countdown starts with 1 unit of the lower cabinet. Change it unfortunately can not be, i have inherited what is. There is also the task of implementing DCIM, (currently accounting is carried out in general in Excel), OpenDCIM best reflects our infrastructure, but nevertheless, it is also necessary to refine what I'm trying to do.

The devices are moved by dragndrop correctly.

Yes, reverse numbering cabinets I screwed up, it does not work, I forgot to test it, but I'm it will fix, if that makes sense also for someone other than me.


If a user sets that first U value to 0, Cab drawing incorrect (this bug, sorry). If trying set negative U, worked protection "Numbers only"

**Comment by dc-admin** [comment]
Is it possible to somehow remove the pool-request, that it does not conflict with others?

**Comment by dc-admin** [comment]
Thanks.

**Pull request closed without merging**
