### PR TITLE
Fixed access to the attributes of objects used in the tooltip

### PR DESCRIPTION
**Pull request by valmison**
The apache logs 

> PHP Notice: Array to string conversion in /var/www/opendcim/scripts/ajax_tooltip.php

 were generated because the attributes of the **$dev** and **$pdu** objects are accessed through concatenation with the array key **$row['Field']** .

For this case there are two solutions:

1. Access object attributes with the key of the array enclosed in braces **$obj->{$row['Field']}**
2. Access the attributes directly without using the array key **$obj->Attribute**

### CODE REVIEW

**Comment by wilpig** [comment]
The curly braces should only be needed in the case where these are used in the middle of a parsed string.  None of these look valid.  What steps are triggering this condition?

**Comment by valmison** [comment]
> The curly braces should only be needed in the case where these are used in the middle of a parsed string. None of these look valid. What steps are triggering this condition?

I really forgot to mention that the warnings in the apache log appear when viewing the tooltip of the device and CDU of a cabinet in cabinavigator.php.
I hope after analysis realize the validity of this pull request and see another way of using the curly braces.

**Comment by wilpig** [comment]
No.  I'm not even going to start picking this apart.  This already works with both openldap and ad.  On the demo site we have it configured for openldap, on my dev site it is configured with AD.  We will be updating documentation and adding debug information as toggle-able option in the configuration to ease implementation troubles.

**Comment by valmison** [comment]
> No. I'm not even going to start picking this apart. This already works with both openldap and ad. On the demo site we have it configured for openldap, on my dev site it is configured with AD. We will be updating documentation and adding debug information as toggle-able option in the configuration to ease implementation troubles.

Okay, but I'd still like the attention to look at my implementation as I believe it's more performative to get user data and groups in just one LDAP query and not use the FOR loop.
What has been customized in the DB and in the configuration.php script, I repeat, makes it easier to fill in the Base Search and Bind DN information that are totally different between OpenLDAP and AD.

**Pull request closed without merging**
