### PR TITLE
Add the config.ini file to hold the config values instead of php code.

### PR DESCRIPTION
**Pull request by paulchubatyy**
So instead of keeping the configuration inside the code it's better to keep it inside the `config.ini` and read from there.

Also, it's backwards compatible.

### CODE REVIEW

**Comment by syndgr** [comment]
Although it's down to the user to make sure they secure their install, if this PR is accepted any documentation needs to be updated so that users know that they need to ensure that config.ini cannot be served up by the web server and therefore disclosing the database name, username and password.

This is why keeping the config within a .php file is probably more preferential and universal. Otherwise any documentation may have to go in to detail on how to create an appropriate .htaccess file for Apache, how to configure nginx etc.

**Comment by timlegge** [comment]
Another project I work on essentially has a config file by:

```
if (file_exists(WEBROOT . 'includes/auth.php')) {
    $config = include WEBROOT . 'includes/auth.php';
    foreach ($config as $key => $value) {
        $this->setConfig($key, $value);
    }
}
    protected function setConfig($key, $value)
    {
        if (!isset($this->$key) || $key == 'kga' || $key == 'database') {
            return;
        }
        $this->$key = $value;
    }
```

includes/auth.php is:

```
<?php
return array(
    'debug'  => 'true',
    'dbhost'  =>' localhost',
    'dbname' => 'dcim',
￼    'dbuser' => 'dcim',
￼    'dbpass' => 'dcim',
￼    'mechanism' = 'Apache',
);
```
Then the values are referenced as:

`dbuser = $this->dbuser;
`
Tim

**Comment by wilpig** [comment]
What benefit does this add? I see complication of an additional parsing file and no real improved security.

**Comment by timlegge** [comment]
Not a lot over the current file.  It does pull the variables in one place for the person installing and avoids needing to add additional security measures for the ini file that is proposed above.

It has similar problems as the current file (and the ini file for that matter) with the need for correct syntax.  A better option would likely be for the installer to ask for the values and take care of storing them appropriately.

I have not had any issues with the current config but compared to a config.ini that would need special attention to secure I like this better.  As you say though it adds an extra file to parse

**Pull request closed without merging**
